/*
 * HackMan3D Control Deck Pro
 * Board selection for ESP32_Display_Panel.
 */

#pragma once

#define ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED 1
#define BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7

#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_MAJOR 1
#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_MINOR 2
#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_PATCH 0
